# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pants-lint
        name: Pants lint
        always_run: false
        description: Runs linters and any formatters in check-only mode
        entry: ./pants --no-dynamic-ui --owners-not-found-behavior=ignore lint
        language: system
        pass_filenames: true
        types: [file, python]
      - id: pants-fmt
        name: Pants autoformat
        always_run: false
        description: Runs formatter on python files
        entry: ./pants --no-dynamic-ui --owners-not-found-behavior=ignore fmt
        language: system
        pass_filenames: true
        types: [file, python]
