FROM python:3.8
LABEL maintainer="Sofiane Bebert <s.bebert@diceytech.co.uk>"

ARG requirements=requirements/dev.txt
ENV DJANGO_SETTINGS_MODULE=djangodocker.settings.local

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY classroom classroom
COPY Makefile /app/
COPY manage.py /app/
COPY requirements/ /app/requirements/ 

RUN make requirements

RUN useradd -m --shell /bin/false app