[GLOBAL]
pants_version = "2.8.1rc1"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]

[python]
interpreter_search_paths = ["<PYENV>", "<PATH>"]

[python-infer]
string_imports = true

[anonymous-telemetry]
enabled = false