# Generated by Django 3.2.13 on 2022-05-26 08:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDemographics",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "user",
                    models.PositiveIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m", "Male"),
                            ("f", "Female"),
                            ("t", "Transgender"),
                            ("o", "Other/Prefer Not to Say"),
                        ],
                        db_index=True,
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "user_ethnicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ea", "East - Asian"),
                            ("as", "Southwest - Asian"),
                            ("ba", "Black - African"),
                            ("bc", "Black - Caribbean"),
                            ("be", "Black - European"),
                            ("me", "Middle Eastern"),
                            ("wa", "White - American"),
                            ("we", "White - European"),
                        ],
                        db_index=True,
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p", "Doctorate"),
                            ("m", "Master's or professional degree"),
                            ("b", "Bachelor's degree"),
                            ("hs", "Secondary/high school"),
                            ("el", "Elementary/primary school"),
                            ("ap", "Apprentice"),
                            ("none", "No formal education"),
                            ("other", "Other education"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Demographic",
                "verbose_name_plural": "User Demographic",
                "ordering": ["created"],
            },
        ),
    ]
