# Generated by Django 2.2.19 on 2021-03-18 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.UUIDField(help_text='School uuid.')),
                ('name', models.CharField(default='Your Classroom Name', help_text='Specifies the displayed name of the classroom', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEnrollement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('classroom_id', models.ForeignKey(blank=True, help_text='The classroom to which this enrollment is attached', null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('classroom_id', 'user_id')},
            },
        ),
    ]
