# Generated by Django 2.2.24 on 2021-08-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroomfeaturerole_classroomroleassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomenrollement',
            old_name='classroom_id',
            new_name='classroom_instance',
        ),
        migrations.AlterUniqueTogether(
            name='classroomenrollement',
            unique_together={('classroom_instance', 'user_id')},
        ),
    ]
