# Run commitlint on the commit messages in a pull request.

name: Lint Commit Messages

on:
  - pull_request
  - workflow_dispatch

jobs:
  commitlint:
    uses: Dicey-Tech/.github/.github/workflows/commitlint.yml@master
